---
title: "Arbeidskrav 1: Arbeidsfysiologisk rapport"
format: pdf
editor: visual
execute: 
  warning: false
  echo: false
  message: false
editor_options: 
  chunk_output_type: console
---

## 

```{r}
library(tidyverse)
library(knitr)
library(readxl)

tabell_deltakere <- read.csv("data/behandlet/behandlet_vo2maks.csv")

tabell_deltakere <- tabell_deltakere |> 
  select(deltager,
         kjonn,
         alder) |>  
  
  distinct() |> 
  
  mutate(kjonn = if_else(kjonn == "m", "Mann", "Kvinne"))

kable(
  tabell_deltakere,
  format = "latex",
  col.names = c("Deltaker", "Kjønn", "Alder (år)"),
  booktabs = TRUE,
  linesep = "") 
```

```{r}
library(ggplot2)
#| label: fig-vo2maks
#| fig-cap: "Forskjell i VO2 maks mellom morgen og kveld"

#FORSLAG 1
behandlede_data <- read.csv("data/behandlet/behandlet_vo2maks.csv")

behandlede_data <- behandlede_data |> 
  mutate(starttidspunkt = factor(starttidspunkt, levels = c("Morgen", "Kveld")))

figur_resultater <- ggplot(data = behandlede_data,
                 aes(deltager, VO2_maks_rel)) +
  
  geom_point(size = 1.5,
color = "black") + 
  
  facet_wrap(~ starttidspunkt) +
  
  labs(
    x = "Deltagere",
    y = "VO2-maks (ml/kg/min)") + 
  
  scale_y_continuous(
    limits = c(45, 70),
    breaks = seq(45, 70, by = 5),
    expand = c(0, 0)) + 
  
  theme_bw()

print(figur_resultater)

ggsave("figurer/figur-vo2maks.png", figur_resultater, 
       width = 12, height = 9, units = "cm")
```

```{r}
library(tidyverse)
library(knitr)
library(readxl)
#| label: fig-vo2maks2
#| fig-cap: "Forskjell i VO2 maks mellom morgen og kveld"

#FORSLAG 2
tabell <- read.csv("data/behandlet/behandlet_vo2maks.csv")

mod <- lm(VO2_maks_rel ~ starttidspunkt + deltager, data = tabell)
pval <- round(coef(summary(mod))[2, 4], 5)


tabell <- tabell |> 
  mutate(starttidspunkt = factor(starttidspunkt, levels = c("Morgen", "Kveld")))

fig_resultater <- ggplot(data = tabell,
                 aes(x = starttidspunkt, y = VO2_maks_rel, group = deltager, color = deltager)) +
  
  geom_line(linewidth = 0.7) + 
  
  geom_point(size = 1.5,
             color = "black",
             fill = "grey") + 
  
  labs(
    x = "Tid på døgnet",
    y = "VO2-maks (ml/kg/min)",
    
    color = "Deltager") + 
  
  scale_y_continuous(
    limits = c(45, 70),
    breaks = seq(45, 70, by = 5),
    expand = c(0, 0)) +  
  
  theme_linedraw() +
  
  annotate("segment", x = 1, xend = 2, y = 67, yend = 67) + 
  annotate("segment",
           x = c(1, 2), 
           xend = c(1, 2),
           y = c(67, 67),
           yend = c(66, 66)) + 
  
  annotate("text", label = paste0("P-verdi = ", pval),
           x = 1.5, y = 68)

print(fig_resultater)

ggsave("figurer/figur-vo2maks2.png", fig_resultater, 
       width = 12, height = 9, units = "cm")

```

```{r}
#|warning: false
#|message: false
#|echo: false

library(tidyverse)
library(knitr)

tabell_resultater <- read.csv("data/behandlet/behandlet_vo2maks.csv")

tabell_resultater <- tabell_resultater |> 
  mutate(starttidspunkt = factor(starttidspunkt, levels = c("Morgen", "Kveld"))) |> 
  
  group_by(starttidspunkt) |> 
  summarise(
    snitt_vo2 = mean(VO2_maks_rel, na.rm = TRUE),
    avvik_vo2 = sd(VO2_maks_rel, na.rm = TRUE),
    snitt_hf = mean(HF_maks, na.rm = TRUE),
    avvik_hf = sd(HF_maks, na.rm = TRUE),
    snitt_laktat = mean(la_maks, na.rm = TRUE),
    avvik_laktat = sd(la_maks, na.rm = TRUE),
    snitt_RER = mean(RER_maks, na.rm = TRUE),
    avvik_RER = sd(RER_maks, na.rm = TRUE),
    snitt_borg = mean(borg_maks, na.rm = TRUE),
    avvik_borg = sd(borg_maks, na.rm = TRUE)
  ) |> 
  
  mutate(
    VO2maks = paste0(round(snitt_vo2, 1), " ± ", round(avvik_vo2, 1)),
    Hjertefrekvens = paste0(round(snitt_hf, 0), " ± ", round(avvik_hf, 0)),
    Laktat = paste0(round(snitt_laktat, 2), " ± ", round(avvik_laktat, 2)),
    RER = paste0(round(snitt_RER, 2), " ± ", round(avvik_RER, 2)),
    Borg = paste0(round(snitt_borg, 0), " ± ", round(avvik_borg, 0))
  ) |> 
  
  select(starttidspunkt, 
         VO2maks, 
         Hjertefrekvens, 
         Laktat, 
         RER, 
         Borg) |> 
  
  pivot_longer(cols = -starttidspunkt, names_to = "Variabel", values_to = "verdi") |> 
  pivot_wider(names_from = starttidspunkt, values_from = "verdi")

kable(tabell_resultater, 
      caption = "Deskriptiv statistikk for morgen- og kveldstester")
```
